<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!--Camera base frame-->
    <joint name="Camera_base_joint" type="fixed">
        <origin xyz="0.06183 0 0.01878" rpy="0 0 0"/>

        <parent link="M_base_link"/>
        <child link="Camera_base_link"/>        
    </joint>

    <link name="Camera_base_link">
        <visual>
            <origin xyz="-${Camera_base_X/2} 0 -${Camera_base_Z/2}" rpy="0 0 0"/>

            <geometry>    
                <box size="${Camera_base_X} ${Camera_base_Y} ${Camera_base_Z}"/>
            </geometry>

            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="-${Camera_base_X/2} 0 -${Camera_base_Z/2}" rpy="0 0 0"/>

            <geometry>    
                <box size="${Camera_base_X} ${Camera_base_Y} ${Camera_base_Z}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${Camera_base_mass}" x="${Camera_base_X}" y="${Camera_base_Y}" z="${Camera_base_Z}">
            <origin xyz="-${Camera_base_X/2} 0 -${Camera_base_Z/2}" rpy="0 0 0"/>

        </xacro:inertial_box>
    </link>

    <!--Camera frame-->
    <joint name="Camera_joint" type="fixed">
        <origin xyz="-0.0027 0 0.01134" rpy="0 0 0"/>

        <parent link="Camera_base_link"/>
        <child link="Camera_link"/>    
    </joint>

    <link name="Camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>    
                <box size="${Camera_X} ${Camera_Y} ${Camera_Z}"/>
            </geometry>

            <material name="green"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>    
                <box size="${Camera_X} ${Camera_Y} ${Camera_Z}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${Camera_mass}" x="${Camera_X}" y="${Camera_Y}" z="${Camera_Z}">
            <origin xyz="0 0 0" rpy="0 0 0"/>

        </xacro:inertial_box>
    </link>

    <!--Camera optical frame-->
    <joint name="Camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${pi/2} 0 -${pi/2}"/>

        <parent link="Camera_link"/>
        <child link="Camera_optical_link"/>    
    </joint>

    <link name="Camera_optical_link"> </link>


    <!-- Gazebo camera setup -->
    <gazebo reference="Camera_link">
        <sensor name="camera" type="camera">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.264</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>1080</width>
                    <height>720</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>Camera_optical_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>