<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!--lidar base frame-->
    <joint name="Lidar_base_joint" type="fixed">
        <origin xyz="0 0 0.0305" rpy="0 0 0"/>

        <parent link="T_base_link"/>
        <child link="Lidar_base_link"/>        
    </joint>

    <link name="Lidar_base_link">
        <visual>
            <origin xyz="0 0 -${Lidar_base_Z/2}" rpy="0 0 0"/>

            <geometry>    
                <box size="${Lidar_base_X} ${Lidar_base_Y} ${Lidar_base_Z}"/>
            </geometry>

            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 -${Lidar_base_Z/2}" rpy="0 0 0"/>

            <geometry>    
                <box size="${Lidar_base_X} ${Lidar_base_Y} ${Lidar_base_Z}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${Lidar_base_mass}" x="${Lidar_base_X}" y="${Lidar_base_Y}" z="${Lidar_base_Z}">
            <origin xyz="0 0 -${Lidar_base_Z/2}" rpy="0 0 0"/>

        </xacro:inertial_box>
    </link>

    <!--Lidar motor frame-->
    <joint name="Lidar_motor_joint" type="continuous">
        <origin xyz="-0.011 0 0.01225" rpy="0 0 0"/>

        <parent link="Lidar_base_link"/>
        <child link="Lidar_motor_link"/>    
        <axis xyz="0 0 1"/>  
    </joint>

    <link name="Lidar_motor_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>    
                <cylinder length="${Lidar_motor_length}" radius="${Lidar_motor_radius}"/>
            </geometry>

            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>          
                <cylinder length="${Lidar_motor_length}" radius="${Lidar_motor_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${Lidar_motor_mass}" length="${Lidar_motor_length}" radius="${Lidar_motor_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>

        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="Lidar_motor_link">
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize> false </visualize>
            <upadet_rate> 10 </upadet_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples> 360 </samples>
                        <resolution> 1 </resolution>
                        <min_angle> -3.14 </min_angle>
                        <max_angle> 3.14 </max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min> 0.1 </min>
                    <max> 12 </max>
                    <resolution> 0.01 </resolution>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument> ~/out:=scan </argument>
                </ros>
                <output_type> sensor_msgs/LaserScan </output_type>
                <frame_name> Lidar_motor_link </frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>