<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!--base link-->
    <link name="base_link"> </link>


    <!--Base footprint-->
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 -0.0341" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="base_footprint"/>        
    </joint>
    
    <link name="base_footprint">
    </link>


    <!--Bottom base-->
    <joint name="B_base_joint" type="fixed">
        <origin xyz="0 0 0.0225" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="B_base_link"/>        
    </joint>

    <link name="B_base_link">
        <visual>
            <origin xyz="0 0 -${B_base_length/2}" rpy="0 0 0"/>
            <geometry>    
                <!--<mesh filename="package://robot_pkg/meshes/base_link.STL" />-->
                <cylinder length="${B_base_length}" radius="${B_base_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 -${B_base_length/2}" rpy="0 0 0"/>
            <geometry>
                <!--<mesh filename="package://robot_pkg/meshes/base_link.STL" />-->            
                <cylinder length="${B_base_length}" radius="${B_base_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${B_base_mass}" length="${B_base_length}" radius="${B_base_radius}">
            <origin xyz="0 0 -${B_base_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!--Left wheel-->
    <joint name="L_wheel_joint" type="continuous">
        <origin xyz="0 0.104 0" rpy="-${pi/2} ${pi/2} 0"/>
        <parent link="base_link"/>
        <child link="L_wheel_link"/>    
        <axis xyz="0 0 1"/>
        <limit effort="0.323" velocity="10.47" />    
    </joint>

    <link name="L_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>    
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>          
                <sphere radius="${wheel_radius}"/>
                <!-- <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/> -->
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!--Right wheel-->
    <joint name="R_wheel_joint" type="continuous">
        <origin xyz="0 -0.104 0" rpy="${pi/2} ${pi/2} 0"/>
        <parent link="base_link"/>
        <child link="R_wheel_link"/>    
        <axis xyz="0 0 -1"/>
        <limit effort="0.323" velocity="10.47" />    
    </joint>

    <link name="R_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>    
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>          
                <sphere radius="${wheel_radius}"/>
                <!-- <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/> -->
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!-- Caster support 1 -->
    <joint name="C_support_1_joint" type="fixed">
        <origin xyz="0.05751 0 -0.005" rpy="0 0 0"/>
        <parent link="B_base_link"/>
        <child link="C_support_1_link"/>    
    </joint>

    <link name="C_support_1_link">
        <visual>
            <origin xyz="0 0 -${C_support_box_Z/2}" rpy="0 0 0"/>
            <geometry>    
                <box size="${C_support_box_X} ${C_support_box_Y} ${C_support_box_Z}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 -${C_support_box_Z/2}" rpy="0 0 0"/>
            <geometry>    
                <box size="${C_support_box_X} ${C_support_box_Y} ${C_support_box_Z}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${C_support_mass}" x="${C_support_box_X}" y="${C_support_box_Y}" z="${C_support_box_Z}">
            <origin xyz="0 0 -${C_support_box_Z/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!--Caster wheel base 1-->
    <joint name="U_base_wheel_1_joint" type="continuous">
        <origin xyz="0 0 -0.013" rpy="${pi} 0 0"/>
        <parent link="C_support_1_link"/>
        <child link="U_base_wheel_1_link"/>    
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="U_base_wheel_1_link">
        <visual>
            <origin xyz="0 0 ${U_base_box_Z/2}" rpy="0 0 0"/>
            <geometry>    
                <box size="${U_base_box_X} ${U_base_box_Y} ${U_base_box_Z}"/>
            </geometry>
            <material name="light_gray"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${U_base_box_Z/2}" rpy="0 0 0"/>
            <geometry>    
                <box size="${U_base_box_X} ${U_base_box_Y} ${U_base_box_Z}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${U_base_mass}" x="${U_base_box_X}" y="${U_base_box_Y}" z="${U_base_box_Z}">
            <origin xyz="0 0 ${U_base_box_Z/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!--Caster wheel 1-->
    <joint name="U_wheel_1_joint" type="continuous">
        <origin xyz="0.016 0 0.0256" rpy="${pi/2} 0 0"/>

        <parent link="U_base_wheel_1_link"/>
        <child link="U_wheel_1_link"/>    
        <axis xyz="0 0 -1"/>   
    </joint>

    <link name="U_wheel_1_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>    
                <cylinder radius="${U_wheel_radius}" length="${U_wheel_thickness}"/>
            </geometry>

            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>    
                <cylinder radius="${U_wheel_radius}" length="${U_wheel_thickness}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${U_wheel_mass}" length="${U_wheel_thickness}" radius="${U_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        
        </xacro:inertial_cylinder>
    </link>


    <!-- Caster support 2 -->
    <joint name="C_support_2_joint" type="fixed">
        <origin xyz="-0.05751 0 -0.005" rpy="0 0 0"/>
        <parent link="B_base_link"/>
        <child link="C_support_2_link"/>    
    </joint>

    <link name="C_support_2_link">
        <visual>
            <origin xyz="0 0 -${C_support_box_Z/2}" rpy="0 0 0"/>
            <geometry>    
                <box size="${C_support_box_X} ${C_support_box_Y} ${C_support_box_Z}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 -${C_support_box_Z/2}" rpy="0 0 0"/>
            <geometry>    
                <box size="${C_support_box_X} ${C_support_box_Y} ${C_support_box_Z}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${C_support_mass}" x="${C_support_box_X}" y="${C_support_box_Y}" z="${C_support_box_Z}">
            <origin xyz="0 0 -${C_support_box_Z/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!--Caster wheel base 2-->
    <joint name="U_base_wheel_2_joint" type="continuous">
        <origin xyz="0 0 -0.013" rpy="${pi} 0 0"/>
        <parent link="C_support_2_link"/>
        <child link="U_base_wheel_2_link"/>    
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="U_base_wheel_2_link">
        <visual>
            <origin xyz="0 0 ${U_base_box_Z/2}" rpy="0 0 0"/>
            <geometry>    
                <box size="${U_base_box_X} ${U_base_box_Y} ${U_base_box_Z}"/>
            </geometry>
            <material name="light_gray"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${U_base_box_Z/2}" rpy="0 0 0"/>
            <geometry>    
                <box size="${U_base_box_X} ${U_base_box_Y} ${U_base_box_Z}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${U_base_mass}" x="${U_base_box_X}" y="${U_base_box_Y}" z="${U_base_box_Z}">
            <origin xyz="0 0 ${U_base_box_Z/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!--Caster wheel 2-->
    <joint name="U_wheel_2_joint" type="continuous">
        <origin xyz="0.016 0 0.0256" rpy="${pi/2} 0 0"/>

        <parent link="U_base_wheel_2_link"/>
        <child link="U_wheel_2_link"/>    
        <axis xyz="0 0 -1"/>   
    </joint>

    <link name="U_wheel_2_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>    
                <cylinder radius="${U_wheel_radius}" length="${U_wheel_thickness}"/>
            </geometry>

            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>    
                <cylinder radius="${U_wheel_radius}" length="${U_wheel_thickness}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${U_wheel_mass}" length="${U_wheel_thickness}" radius="${U_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        
        </xacro:inertial_cylinder>
    </link>


    <!--Support A-->
    <joint name="Support_A_joint" type="fixed">
        <origin xyz="0 0 0.02" rpy="0 0 0"/>
        <parent link="B_base_link"/>
        <child link="Support_A_link"/>    
    </joint>

    <link name="Support_A_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>    
                <box size="${Support_AX} ${Support_AY} ${Support_AZ}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>    
                <box size="${Support_AX} ${Support_AY} ${Support_AZ}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${Support_A_mass}" x="${Support_AX}" y="${Support_AY}" z="${Support_AZ}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!--Middle base-->
    <joint name="M_base_joint" type="fixed">
        <origin xyz="0 0 0.025" rpy="0 0 0"/>
        <parent link="Support_A_link"/>
        <child link="M_base_link"/>        
    </joint>

    <link name="M_base_link">
        <visual>
            <origin xyz="0 0 -${MT_length/2}" rpy="0 0 0"/>
            <geometry>    
                <cylinder length="${MT_length}" radius="${MT_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="0 0 -${MT_length/2}" rpy="0 0 0"/>
            <geometry>          
                <cylinder length="${MT_length}" radius="${MT_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${MT_mass}" length="${MT_length}" radius="${MT_radius}">
            <origin xyz="0 0 -${MT_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!--Support B-->
    <joint name="Support_B_joint" type="fixed">
        <origin xyz="0 0 0.0255" rpy="0 0 0"/>
        <parent link="M_base_link"/>
        <child link="Support_B_link"/>    
    </joint>

    <link name="Support_B_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>    
                <box size="${Support_BX} ${Support_BY} ${Support_BZ}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>    
                <box size="${Support_BX} ${Support_BY} ${Support_BZ}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${Support_B_mass}" x="${Support_BX}" y="${Support_BY}" z="${Support_BZ}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!--Top base-->
    <joint name="T_base_joint" type="fixed">
        <origin xyz="0 0 0.0305" rpy="0 0 0"/>
        <parent link="Support_B_link"/>
        <child link="T_base_link"/>        
    </joint>

    <link name="T_base_link">
        <visual>
            <origin xyz="0 0 -${MT_length/2}" rpy="0 0 0"/>
            <geometry>    
                <cylinder length="${MT_length}" radius="${MT_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 -${MT_length/2}" rpy="0 0 0"/>
            <geometry>          
                <cylinder length="${MT_length}" radius="${MT_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${MT_mass}" length="${MT_length}" radius="${MT_radius}">
            <origin xyz="0 0 -${MT_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

</robot>