<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="TTR01">

    <!--world frame-->
    <xacro:include filename="parameters.xacro"/>

    <link name="World"> </link>

    <joint name="World_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>

        <parent link="World"/>
        <child link="base_link"/>        
    </joint>

    <!--base frame-->
    <xacro:property name="B_base_length" value="0.005"/>
    <xacro:property name="B_base_radius" value="0.178"/>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${B_base_length/2}" rpy="0 0 0"/>

            <geometry>    
                <!--<mesh filename="package://robot_pkg/meshes/base_link.STL" />-->            
                <cylinder length="${B_base_length}" radius="${B_base_radius}"/>
            </geometry>

            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${B_base_length/2}" rpy="0 0 0"/>

            <geometry>
                <cylinder length="${B_base_length}" radius="${B_base_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.9" length="${B_base_length}" radius="${B_base_radius}">
            <origin xyz="0 0 0.034" rpy="0 0 0"/>

        </xacro:inertial_cylinder>
    </link>

    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 0.034" rpy="0 0 0"/>

        <parent link="World"/>
        <child link="base_link"/>        
    </joint>
    <xacro:include filename="gazebo_setup.xacro"/>

</robot>